In [ ]:
Interesting_regions =   [4, 5, 32, 33, 44, 45, 48, 49]
Interesting_right =   [5, 33, 45, 49]
Interesting_left =   [4, 32, 44, 48]

Good_subjects =         [0, 2, 5, 9, 12, 14]
Ok_subjects =           [1, 3, 4, 6, 11, 13, 19]
Other_subjects = [i for i in range(20) if i not in Ok_subjects and i not in Good_subjects]

Subjects_dict = {"Good_subjects": Good_subjects, "Ok_subjects":Ok_subjects, "Other_subjects":Other_subjects}

data_folder="../Data/"

from BCI_Library import read_subject, plot_brain, train_models, extract_features_more_bands, select_regions_Cohen_effect_size, compute_welch
from BCI_Library import saveresults_pickle, select_rows, compute_welch, extract_features_from_spectra_more_bands,cohens_d_per_columm, select_rows

In [ ]:
import pandas as pd

Rows = pd.DataFrame({
    "ROIs": [],
    "NROIs":[],
    "DataType": [],
    "freqs_band": [],  
    "subject": [],
    "Classifier": [],
    "Performance": [],
    "Features": [],
    "Comments": [],
    "Date": [],
    "Personalized_Freq_Range":[]
})

Rows.to_pickle("../Results/xxxxx.pkl")

# TEST

In [5]:
import pandas as pd
selections = pd.read_pickle("../Results/BCI_Performances/BCI_Performances_Important_regions.pkl")

In [8]:
set(selections["Region Selection"])

{'No Important Regions',
 'Only one region',
 'Yes Important Regions',
 'Yes Important Regions - all',
 'Yes Important Regions - left',
 'Yes Important Regions - tight'}

In [13]:
selections[selections["Region Selection"]=="Yes Important Regions - all"]

,ROIs,NROIs,DataType,freqs_band,subject,Classifier,Accuracy,Features,Region Selection,Date,Personalized_Freq_Range,Comments
2100,"[4, 5, 32, 33, 44, 45, 48, 49]",8.0,EEG,"((4, 8), (8, 12), (12, 30))",0.0,LDA,"[0.84375, 0.8387096774193549, 0.74193548387096...",PowerSpectra - MeanMax band,Yes Important Regions - all,2025-12-02,False,-
2101,"[4, 5, 32, 33, 44, 45, 48, 49]",8.0,EEG,"((4, 8), (8, 12), (12, 30))",1.0,LDA,"[0.5526315789473685, 0.7631578947368421, 0.710...",PowerSpectra - MeanMax band,Yes Important Regions - all,2025-12-02,False,-
2102,"[4, 5, 32, 33, 44, 45, 48, 49]",8.0,EEG,"((4, 8), (8, 12), (12, 30))",2.0,LDA,"[0.9230769230769231, 0.8717948717948718, 0.763...",PowerSpectra - MeanMax band,Yes Important Regions - all,2025-12-02,False,-
2103,"[4, 5, 32, 33, 44, 45, 48, 49]",8.0,EEG,"((4, 8), (8, 12), (12, 30))",3.0,LDA,"[0.8157894736842105, 0.8421052631578947, 0.763...",PowerSpectra - MeanMax band,Yes Important Regions - all,2025-12-02,False,-
2104,"[4, 5, 32, 33, 44, 45, 48, 49]",8.0,EEG,"((4, 8), (8, 12), (12, 30))",4.0,LDA,"[0.7692307692307693, 0.6666666666666666, 0.736...",PowerSpectra - MeanMax band,Yes Important Regions - all,2025-12-02,False,-
...,...,...,...,...,...,...,...,...,...,...,...,...
2315,"[[4, 5, 32, 33, 44, 45, 48, 49], [4, 5, 32, 33...",8.0,EEG concat MEG,"((4, 8), (8, 12), (12, 30))",15.0,RandomForest,"[0.7435897435897436, 0.6666666666666666, 0.815...",PowerSpectra - MeanMax band,Yes Important Regions - all,2025-12-02,False,-
2316,"[[4, 5, 32, 33, 44, 45, 48, 49], [4, 5, 32, 33...",8.0,EEG concat MEG,"((4, 8), (8, 12), (12, 30))",16.0,RandomForest,"[0.7878787878787878, 0.6666666666666666, 0.636...",PowerSpectra - MeanMax band,Yes Important Regions - all,2025-12-02,False,-
2317,"[[4, 5, 32, 33, 44, 45, 48, 49], [4, 5, 32, 33...",8.0,EEG concat MEG,"((4, 8), (8, 12), (12, 30))",17.0,RandomForest,"[0.7692307692307693, 0.7948717948717948, 0.789...",PowerSpectra - MeanMax band,Yes Important Regions - all,2025-12-02,False,-
2318,"[[4, 5, 32, 33, 44, 45, 48, 49], [4, 5, 32, 33...",8.0,EEG concat MEG,"((4, 8), (8, 12), (12, 30))",18.0,RandomForest,"[0.8, 0.6857142857142857, 0.6857142857142857, ...",PowerSpectra - MeanMax band,Yes Important Regions - all,2025-12-02,False,-
2319,"[[4, 5, 32, 33, 44, 45, 48, 49], [4, 5, 32, 33...",8.0,EEG concat MEG,"((4, 8), (8, 12), (12, 30))",19.0,RandomForest,"[0.8421052631578947, 0.7631578947368421, 0.736...",PowerSpectra - MeanMax band,Yes Important Regions - all,2025-12-02,False,-

In [ ]:
# import os
# import pandas as pd

# folder1 = "../Results/BCI_Performances"


# for filename in os.listdir(folder1):
#     if filename.endswith(".pkl"):
#         file_path = os.path.join(folder1, filename)
        
#         # read dataframe
#         df = pd.read_pickle(file_path)
        
#         # rename column if present
#         if "Comments" in df.columns:
#             df = df.rename(columns={"aasas": "Region Selection"})
#             df["Comments"] = "-"

#         output_path = os.path.join(folder1, filename)
#         df.to_pickle(output_path)

In [9]:
df.head()

,ROIs,NROIs,DataType,freqs_band,subject,Classifier,Accuracy,Features,Region Selection,Date,Personalized_Freq_Range,Comments
0,"[[23], [27]]",1.0,EEG concat MEG,"((4, 8), (8, 12), (12, 30))",0.0,RandomForest,"[1.0, 1.0, 0.8709677419354839, 0.9032258064516...",PowerSpectra - MeanMax band,No Important Regions,2025-12-01,False,-
1,"[[23, 15, 14], [27, 43, 23]]",3.0,EEG concat MEG,"((4, 8), (8, 12), (12, 30))",0.0,RandomForest,"[0.96875, 1.0, 0.9354838709677419, 0.903225806...",PowerSpectra - MeanMax band,No Important Regions,2025-12-01,False,-
2,"[[23, 15, 14, 22, 17], [27, 43, 23, 15, 22]]",5.0,EEG concat MEG,"((4, 8), (8, 12), (12, 30))",0.0,RandomForest,"[1.0, 1.0, 0.967741935483871, 0.93548387096774...",PowerSpectra - MeanMax band,No Important Regions,2025-12-01,False,-
3,"[[23, 15, 14, 22, 17, 51, 50], [27, 43, 23, 15...",7.0,EEG concat MEG,"((4, 8), (8, 12), (12, 30))",0.0,RandomForest,"[1.0, 0.967741935483871, 0.967741935483871, 0....",PowerSpectra - MeanMax band,No Important Regions,2025-12-01,False,-
4,"[[23, 15, 14, 22, 17, 51, 50, 58, 35], [27, 43...",9.0,EEG concat MEG,"((4, 8), (8, 12), (12, 30))",0.0,RandomForest,"[0.96875, 1.0, 0.967741935483871, 0.9354838709...",PowerSpectra - MeanMax band,No Important Regions,2025-12-01,False,-